# Generated by Django 3.1.5 on 2021-01-23 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhaar', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('category', models.CharField(choices=[('Health Worker/Frontline Worker', 1.1), ('Senior Citizens', 1.2), ('People with Comorbidities', 1.3), ('Others', 1.4)], max_length=100)),
                ('state', models.CharField(choices=[('Uttar Pradesh', 'Uttar Pradesh'), ('Maharashtra', 'Maharashtra'), ('Kerala', 'Kerala'), ('Odisha', 'Odisha'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Bihar', 'Bihar'), ('Rajasthan', 'Rajasthan'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Gujarat', 'Gujarat'), ('Karnataka', 'Karnataka'), ('West Bengal', 'West Bengal'), ('Chandigarh', 'Chandigarh'), ('Punjab', 'Punjab'), ('Delhi', 'Delhi'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Mizoram', 'Mizoram'), ('Tripura', 'Tripura'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Nagaland', 'Nagaland'), ('Meghalaya', 'Meghalaya'), ('Manipur', 'Manipur'), ('Sikkim', 'Sikkim'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Puducherry', 'Puducherry'), ('Jharkhand', 'Jharkhand'), ('Goa', 'Goa'), ('Assam', 'Assam'), ('Haryana', 'Haryana'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Uttarakhand', 'Uttarakhand'), ('Chhattisgarh', 'Chhattisgarh')], max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')])),
                ('covid', models.IntegerField()),
                ('smoker', models.IntegerField()),
                ('hbp_hyt', models.IntegerField()),
                ('respiratory', models.IntegerField()),
                ('asthama', models.IntegerField(choices=[('With no recent OCS use', 1.2), ('With recent OCS use', 1.1)])),
                ('chd', models.IntegerField()),
                ('diabetes', models.IntegerField()),
                ('cancer_non', models.IntegerField()),
                ('hmt', models.IntegerField(choices=[('Diagnosed <1 year ago', 1.1), ('Diagnosed\xa0≥5 years ago', 1.2), ('Diagnosed 1–4.9 years ago', 1.3)])),
                ('reduced_kidney', models.IntegerField(choices=[('eFGR 30-60', 1.2), ('eFGR <30', 1.1)])),
                ('kidney_dialysis', models.IntegerField()),
                ('liver_disease', models.IntegerField()),
                ('other_neuro', models.IntegerField()),
                ('organ_transplant', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
    ]
