# Generated by Django 3.1.5 on 2021-01-23 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalmodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='medicalmodel',
            name='adhaar',
        ),
        migrations.RemoveField(
            model_name='medicalmodel',
            name='age',
        ),
        migrations.RemoveField(
            model_name='medicalmodel',
            name='asthama',
        ),
        migrations.RemoveField(
            model_name='medicalmodel',
            name='cancer_non',
        ),
        migrations.RemoveField(
            model_name='medicalmodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='medicalmodel',
            name='chd',
        ),
        migrations.RemoveField(
            model_name='medicalmodel',
            name='diabetes',
        ),
        migrations.RemoveField(
            model_name='medicalmodel',
            name='district',
        ),
        migrations.RemoveField(
            model_name='medicalmodel',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='medicalmodel',
            name='hbp_hyt',
        ),
        migrations.RemoveField(
            model_name='medicalmodel',
            name='hmt',
        ),
        migrations.RemoveField(
            model_name='medicalmodel',
            name='kidney_dialysis',
        ),
        migrations.RemoveField(
            model_name='medicalmodel',
            name='liver_disease',
        ),
        migrations.RemoveField(
            model_name='medicalmodel',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='medicalmodel',
            name='organ_transplant',
        ),
        migrations.RemoveField(
            model_name='medicalmodel',
            name='other_neuro',
        ),
        migrations.RemoveField(
            model_name='medicalmodel',
            name='reduced_kidney',
        ),
        migrations.RemoveField(
            model_name='medicalmodel',
            name='respiratory',
        ),
        migrations.RemoveField(
            model_name='medicalmodel',
            name='smoker',
        ),
        migrations.RemoveField(
            model_name='medicalmodel',
            name='state',
        ),
        migrations.RemoveField(
            model_name='medicalmodel',
            name='user',
        ),
    ]
