# Generated by Django 3.1.5 on 2021-01-24 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20210124_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalmodel',
            name='adhaar',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmodel',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmodel',
            name='cancer_non',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmodel',
            name='category',
            field=models.CharField(choices=[('Health Worker/Frontline Worker', 1.1), ('Senior Citizens', 1.2), ('People with Comorbidities', 1.3), ('Others', 1.4)], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmodel',
            name='chd',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmodel',
            name='diabetes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmodel',
            name='district',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmodel',
            name='gender',
            field=models.IntegerField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmodel',
            name='hbp_hyt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmodel',
            name='hmt',
            field=models.IntegerField(choices=[('Diagnosed <1 year ago', 1.1), ('Diagnosed\xa0≥5 years ago', 1.2), ('Diagnosed 1–4.9 years ago', 1.3)], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmodel',
            name='kidney_dialysis',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmodel',
            name='liver_disease',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmodel',
            name='mobile',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmodel',
            name='organ_transplant',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmodel',
            name='other_neuro',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmodel',
            name='reduced_kidney',
            field=models.IntegerField(choices=[('eFGR 30-60', 1.2), ('eFGR <30', 1.1)], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmodel',
            name='respiratory',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmodel',
            name='smoker',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmodel',
            name='state',
            field=models.CharField(choices=[('Uttar Pradesh', 'Uttar Pradesh'), ('Maharashtra', 'Maharashtra'), ('Kerala', 'Kerala'), ('Odisha', 'Odisha'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Bihar', 'Bihar'), ('Rajasthan', 'Rajasthan'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Gujarat', 'Gujarat'), ('Karnataka', 'Karnataka'), ('West Bengal', 'West Bengal'), ('Chandigarh', 'Chandigarh'), ('Punjab', 'Punjab'), ('Delhi', 'Delhi'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Mizoram', 'Mizoram'), ('Tripura', 'Tripura'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Nagaland', 'Nagaland'), ('Meghalaya', 'Meghalaya'), ('Manipur', 'Manipur'), ('Sikkim', 'Sikkim'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Puducherry', 'Puducherry'), ('Jharkhand', 'Jharkhand'), ('Goa', 'Goa'), ('Assam', 'Assam'), ('Haryana', 'Haryana'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Uttarakhand', 'Uttarakhand'), ('Chhattisgarh', 'Chhattisgarh')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmodel',
            name='strk_dmtia',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmodel',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
