# Generated by Django 3.1.5 on 2021-01-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210124_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalmodel',
            name='pincode',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalmodel',
            name='adhaar',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='medicalmodel',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicalmodel',
            name='gender',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicalmodel',
            name='hmt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medicalmodel',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='medicalmodel',
            name='reduced_kidney',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medicalmodel',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
