# Generated by Django 3.1.5 on 2021-01-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210124_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalmodel',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
