# Generated by Django 3.1.5 on 2021-02-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210209_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalmodel',
            options={},
        ),
        migrations.RenameField(
            model_name='medicalmodel',
            old_name='category',
            new_name='economy_score',
        ),
        migrations.AddField(
            model_name='medicalmodel',
            name='income',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmodel',
            name='work_status',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
