# Generated by Django 3.1.5 on 2021-01-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210124_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalmodel',
            name='age',
            field=models.CharField(max_length=100),
        ),
    ]
