# Generated by Django 3.1.5 on 2021-02-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210209_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalmodel',
            name='work_status',
            field=models.IntegerField(),
        ),
    ]
