# Generated by Django 3.1.5 on 2021-01-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210124_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalmodel',
            name='eligibility_score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmodel',
            name='no_illness',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalmodel',
            name='occupation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalmodel',
            name='category',
            field=models.IntegerField(max_length=20),
        ),
    ]
