# Generated by Django 3.1.5 on 2021-02-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210209_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalmodel',
            name='vaccine_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
