# Generated by Django 3.1.5 on 2021-01-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210124_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalmodel',
            name='category',
            field=models.IntegerField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='medicalmodel',
            name='eligibility_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='medicalmodel',
            name='no_illness',
            field=models.IntegerField(null=True),
        ),
    ]
