# Generated by Django 3.1.5 on 2021-02-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210210_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalmodel',
            name='date1',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='medicalmodel',
            name='date2',
            field=models.DateField(null=True),
        ),
    ]
