# Generated by Django 3.1.5 on 2021-01-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210124_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalmodel',
            name='illness_score',
            field=models.FloatField(null=True),
        ),
    ]
