# Generated by Django 3.1.5 on 2021-02-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210211_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalmodel',
            name='date1',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='medicalmodel',
            name='date2',
            field=models.DateTimeField(null=True),
        ),
    ]
