# Generated by Django 3.1.5 on 2021-01-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statemodel',
            name='hospital_beds',
        ),
        migrations.AddField(
            model_name='statemodel',
            name='death_rate',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
    ]
